### ISSUE TITLE
Should python-docker be installed by default?

### ISSUE THREAD

**Issue by noelmcloughlin** [saltstack-formulas/docker-formula#185]
There may be a bug in init.sls (not 100% sure). Basically `docker.install_docker_py` is False by default so the state to install python-docker never runs - but surely python-docker is hard requirement?

**Comment by noelmcloughlin** [comment]
Looks like formula  should choose `docker` not `docker-py` (or both).
```
[ERROR   ] An exception occurred in this state: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1913, in call
    **cdata['kwargs'])
  File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1898, in wrapper
    return f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/states/docker_image.py", line 243, in present
    image_info = __salt__['docker.inspect_image'](full_image)
  File "/usr/lib/python2.7/dist-packages/salt/modules/dockermod.py", line 1828, in inspect_image
    ret = _client_wrapper('inspect_image', name)
  File "/usr/lib/python2.7/dist-packages/salt/modules/dockermod.py", line 414, in wrapper
    __context__['docker.client'] = _get_client(timeout=timeout, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/modules/dockermod.py", line 378, in _get_client
    ret = docker.APIClient(**client_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/docker/api/client.py", line 118, in __init__
    config_dict=self._general_configs
TypeError: load_config() got an unexpected keyword argument 'config_dict'
```

**Comment by noelmcloughlin** [comment]
Updated #186  to set `docker_package: docker` to defaults.yaml.  

That is correct package for Ubuntu not docker-py.

**Comment by jose-vbh** [comment]
Besides setting install_docker_py to true, you also need to set python_package: docker in the pillar
