### ISSUE TITLE
MacOS: No available formula with the name "docker-ce"

### ISSUE THREAD

**Issue by noelmcloughlin** [saltstack-formulas/docker-formula#209]
Formula fails on MacOS.
```
ID: docker-package
    Function: pkg.installed
        Name: docker-ce
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/local/Cellar/salt/2019.2.0_1/libexec/lib/python3.7/site-packages/salt/state.py", line 1933, in call
                  **cdata['kwargs'])
                File "/usr/local/Cellar/salt/2019.2.0_1/libexec/lib/python3.7/site-packages/salt/loader.py", line 1939, in wrapper
                  return f(*args, **kwargs)
                File "/usr/local/Cellar/salt/2019.2.0_1/libexec/lib/python3.7/site-packages/salt/states/pkg.py", line 1563, in installed
                  **kwargs)
                File "/usr/local/Cellar/salt/2019.2.0_1/libexec/lib/python3.7/site-packages/salt/states/pkg.py", line 692, in _find_install_targets
                  **kwargs)
                File "/usr/local/Cellar/salt/2019.2.0_1/libexec/lib/python3.7/site-packages/salt/modules/mac_brew.py", line 208, in latest_version
                  versions_dict = dict((key, get_version(val)) for key, val in six.iteritems(_info(*names)))
                File "/usr/local/Cellar/salt/2019.2.0_1/libexec/lib/python3.7/site-packages/salt/modules/mac_brew.py", line 315, in _info
                  brew_result = _call_brew(cmd)
                File "/usr/local/Cellar/salt/2019.2.0_1/libexec/lib/python3.7/site-packages/salt/modules/mac_brew.py", line 95, in _call_brew
                  info={'result': result})
              salt.exceptions.CommandExecutionError: Brew command failed. Additional info follows:
              
              result:
                  ----------
                  pid:
                      41372
                  retcode:
                      1
                  stderr:
                      Error: No available formula with the name "docker-ce"
                  stdout: 
```

**Comment by noelmcloughlin** [comment]
Resolved by #222
